name: Advanced Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Print Hello World
        run: echo "Hello, World!"
        
                
        
      
