name: Advanced Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Print Hello World
        run: echo "Hello, World!"

  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        
      - name: Notify on Failure
        if: failure()
        uses: Ilshidur/action-discord@master
        with:
          status: ${{ job.status }}
          text: "The tests in the 'advanced' job failed. Check the workflow for details."
          channel: ${{ env.DISCORD_CHANNEL_ID }}
        env:
          DISCORD_CHANNEL_ID: "1199353991922983134"
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        
  deploy_to_s3:
            runs-on: ubuntu-latest
          
            steps:
              - name: Checkout Repository
                uses: actions/checkout@v2.5.0
                with:
                  fetch-depth: 0
          
              - name: Set up AWS CLI
                uses: aws-actions/configure-aws-credentials@v1
                with:
                  aws-access-key-id: "AKIAQTVBFA4455PWXHOA"
                  aws-secret-access-key: "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"
                  aws-region: 'eu-north-1'
                env:
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
              - name: Deploy to AWS S3
                run: aws s3 sync ./dist s3://saof20122003bucket

  additional_job_docker_build_push:
                  runs-on: ubuntu-latest
                
                  steps:
                    - name: Checkout Repository
                      uses: actions/checkout@v2.5.0
                      with:
                        fetch-depth: 0
                
                    - name: Set up Docker
                      uses: docker/setup-buildx-action@v1

                    - name: Log in to Docker
                      run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
                      env:
                          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

                    - name: Build and Push Docker Image
                      run: |
                        docker build -t gittest .
                        docker tag gittest 444sofiane/gittest:latest
                        docker push 444sofiane/gittest:latest
                
        
      
