name: Advanced Workflow

on:
  push:
    branches:
      - master

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Print Hello World
        run: echo "Hello, World!"

  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'


      - name: Run Tests
        run: npm test
        
      - name: Notify on Failure
        if: failure()
        uses: 8398a7/action-slack@v2
        with:
            status: ${{ job.status }}
            text: "The tests in the 'advanced' job failed. Check the workflow for details."
            author_name: "Notifying Bot"
            mention: "channel"
            slack_discord_url: ${{ env.DISCORD_WEBHOOK_URL }}
        env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
            SLACK_CHANNEL: "#gitactions-notifying"
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
