name: Basic Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.5.0  # Specify the latest version
        with:
          fetch-depth: 0  # Fetch all history for proper version calculation

      - name: Print Hello World
        run: echo "Hello, World!"
