name: run_unit_tests

on:
  push:
    branches: master

jobs:
    run_unit_tests:
        runs-on: ubuntu-latest

        steps:

        - name: Checkout code
          uses: actions/checkout@v2
          
        - name: Install Criterion
          run: sudo apt-get install -y libcriterion-dev
        
        - name: Build
          run: gcc -o tests_bin tests/tests.c -lcriterion && ./tests_bin

    
    